services:
  - type: web
    name: youtube-video-combiner
    env: node
    buildCommand: |
      chmod +x ./bin/ffmpeg && \
      chmod +x ./bin/ffprobe && \
      chmod +x ./bin/yt-dlp && \
      chmod +x ./.bin/ffmpeg && \
      chmod +x ./.bin/ffprobe && \
      chmod +x ./.bin/yt-dlp && \
      chmod +x /bin/ffmpeg && \
      chmod +x /bin/ffprobe && \
      chmod +x /bin/yt-dlp && \
      npm install && \
      npm run build
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 10000
