services:
  - type: web
    name: youtube-video-combiner
    env: node
    buildCommand: chmod +x install_deps.sh && ./install_deps.sh && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 10000